/* embedded fonts: [Fonts] section, uuencoded like Aegisub */
let F=[];
const u8enc=b=>{let o='';const n=b.length;for(let i=0;i<n;i+=3){const a=b[i],c=i+1<n?b[i+1]:0,d=i+2<n?b[i+2]:0,k=[a>>2,((a&3)<<4)|(c>>4),((c&15)<<2)|(d>>6),d&63],m=Math.min(4,n-i+1);for(let j=0;j<m;j++)o+=String.fromCharCode(k[j]+33)}const L=[];for(let i=0;i<o.length;i+=80)L.push(o.slice(i,i+80));return L};
const u8dec=s=>{const out=[];for(let i=0;i<s.length;i+=4){const q=[];for(let j=0;j<4&&i+j<s.length;j++)q.push((s.charCodeAt(i+j)-33)&63);if(q.length<2)break;out.push(((q[0]<<2)|(q[1]>>4))&255);if(q.length>2)out.push((((q[1]&15)<<4)|(q[2]>>2))&255);if(q.length>3)out.push((((q[2]&3)<<6)|q[3])&255)}return new Uint8Array(out)};
function fontNames(buf){const v=new DataView(buf),tg=n=>String.fromCharCode(v.getUint8(n),v.getUint8(n+1),v.getUint8(n+2),v.getUint8(n+3)),t0=tg(0);if(!['\0\x01\0\0','OTTO','true','ttcf'].includes(t0))return null;const o=t0==='ttcf'?v.getUint32(12):0,nt=v.getUint16(o+4);let no=-1;for(let i=0;i<nt;i++){const r=o+12+i*16;if(tg(r)==='name'){no=v.getUint32(r+8);break}}if(no<0)return{};const cnt=v.getUint16(no+2),so=no+v.getUint16(no+4),best={};for(let i=0;i<cnt;i++){const r=no+6+i*12,pl=v.getUint16(r),id=v.getUint16(r+6),len=v.getUint16(r+8),off=so+v.getUint16(r+10);if(id!==1&&id!==4)continue;let s='';if(pl===3||pl===0)for(let j=0;j+1<len;j+=2)s+=String.fromCharCode(v.getUint16(off+j));else if(pl===1)for(let j=0;j<len;j++)s+=String.fromCharCode(v.getUint8(off+j));else continue;const p=pl===3?(v.getUint16(r+4)===0x409?3:2):1;if(s&&(!best[id]||p>best[id].p))best[id]={s,p}}return{family:best[1]&&best[1].s,full:best[4]&&best[4].s}}
async function regFace(x){try{const ff=new FontFace(x.family,x.bytes.slice().buffer);await ff.load();document.fonts.add(ff);x.face=ff}catch(e){x.bad=1}}
const fontLines=()=>F.length?['','[Fonts]',...F.flatMap(x=>['fontname: '+x.file,...u8enc(x.bytes)])]:[];
function fontList(){const dl=$('#fl');if(!dl)return;dl.querySelectorAll('[data-e]').forEach(o=>o.remove());F.forEach(x=>{const o=document.createElement('option');o.value=x.family;o.dataset.e=1;dl.prepend(o)})}
const saveFonts=()=>idb('put','f',F.map(x=>({file:x.file,family:x.family,full:x.full,bytes:x.bytes}))).catch(()=>{});
async function restoreFonts(a){F=[];for(const x of a||[]){const o={file:x.file,family:x.family,full:x.full,bytes:new Uint8Array(x.bytes)};F.push(o);await regFace(o)}fontList()}
async function loadFileFonts(list){F.forEach(x=>x.face&&document.fonts.delete(x.face));F=[];for(const x of list){const bytes=u8dec(x.data);if(bytes.length<64)continue;let n={};try{n=fontNames(bytes.buffer)||{}}catch(e){}const o={file:x.file,family:n.family||x.file.replace(/_\d+\.\w+$/,'').replace(/\.\w+$/,''),full:n.full,bytes};F.push(o);await regFace(o)}fontList();saveFonts()}
async function addFont(f){try{const bytes=new Uint8Array(await f.arrayBuffer()),n=fontNames(bytes.buffer);if(!n)return toast('Use a .ttf, .otf or .ttc font file');const family=n.family||f.name.replace(/\.\w+$/,'');if(F.some(x=>x.family===family&&x.bytes.length===bytes.length))return toast(family+' is already embedded');const ext=(f.name.match(/\.(ttf|otf|ttc)$/i)||['','ttf'])[1].toLowerCase(),o={file:family.replace(/[^\w.-]+/g,'_')+'_0.'+ext,family,full:n.full,bytes};await regFace(o);if(o.bad)return toast('The browser could not read that font');F.push(o);saveFonts();fontList();const S=A.styles[ss];if(S){S.fontname=family.replace(/,/g,'');commit('font')}all();toast(family+' embedded and applied to '+(S?S.name:'style'))}catch(e){toast('Could not read that font')}}
function removeFont(x){if(x.face)document.fonts.delete(x.face);F=F.filter(y=>y!==x);saveFonts();fontList();dirty=1;renderStyles()}
